return {
	Version = "1.3.2",
	Entry = "Main",
	Modules = {
		Build = "src/Build.lua",
		Util = "src/Core/Util.lua",
		Janitor = "src/Core/Janitor.lua",
		FileSystem = "src/Core/FileSystem.lua",
		ControlRegistry = "src/Core/ControlRegistry.lua",
		ConfigManager = "src/Core/ConfigManager.lua",
		SessionManager = "src/Core/SessionManager.lua",
		ModuleManager = "src/Core/ModuleManager.lua",
		UIManager = "src/Core/UIManager.lua",
		MacLibProvider = "src/Core/MacLibProvider.lua",
		GameAdapter = "src/Core/GameAdapter.lua",
		RewardScanner = "src/Core/RewardScanner.lua",
		Misc = "src/Modules/Misc.lua",
		AutoClaim = "src/Modules/AutoClaim.lua",
		Performance = "src/Modules/Performance.lua",
		Settings = "src/Modules/Settings.lua",
		Main = "src/Main.lua",
	},
}
