return {
	Version = "1.7.1",
	Entry = "Main",
	Modules = {
		Build = "src/Build.lua",
		Util = "src/Core/Util.lua",
		Janitor = "src/Core/Janitor.lua",
		FileSystem = "src/Core/FileSystem.lua",
		ControlRegistry = "src/Core/ControlRegistry.lua",
		ConfigManager = "src/Core/ConfigManager.lua",
		SessionManager = "src/Core/SessionManager.lua",
		ModuleManager = "src/Core/ModuleManager.lua",
		UIManager = "src/Core/UIManager.lua",
		MacLibProvider = "src/Core/MacLibProvider.lua",
		GameAdapter = "src/Core/GameAdapter.lua",
		JoinCatalog = "src/Core/JoinCatalog.lua",
		JoinCoordinator = "src/Core/JoinCoordinator.lua",
		RewardScanner = "src/Core/RewardScanner.lua",
		AutomationCatalog = "src/Core/AutomationCatalog.lua",
		ResultsHub = "src/Core/ResultsHub.lua",
		WebhookReporter = "src/Core/WebhookReporter.lua",
		JoinStory = "src/Modules/JoinStory.lua",
		JoinChallenge = "src/Modules/JoinChallenge.lua",
		JoinEvent = "src/Modules/JoinEvent.lua",
		JoinRaid = "src/Modules/JoinRaid.lua",
		GameMatch = "src/Modules/GameMatch.lua",
		GameEnd = "src/Modules/GameEnd.lua",
		Webhook = "src/Modules/Webhook.lua",
		Misc = "src/Modules/Misc.lua",
		AutoClaim = "src/Modules/AutoClaim.lua",
		AutoSummon = "src/Modules/AutoSummon.lua",
		Performance = "src/Modules/Performance.lua",
		AutoTraitReroll = "src/Modules/AutoTraitReroll.lua",
		Settings = "src/Modules/Settings.lua",
		Main = "src/Main.lua",
	},
}
